import { expect, test } from "./workspace-test";

test("creates an untitled draft from file operations without creating a project file", async ({ page }) => {
  await page.goto("/");
  await expect(page.locator("#run-script-button")).toBeEnabled();
  await page.locator("#project-file-tools > summary").click();
  await expect(page.locator("#project-file-path")).toHaveCount(0);
  await page.locator("#project-file-create").click();
  await expect(page.getByRole("tab", { name: "無題", exact: true })).toHaveAttribute("aria-selected", "true");
  await expect(page.locator("#code-editor")).toHaveValue("");
  await page.locator("#code-editor").fill("answer = 42\n");
  await expect(page.locator("#draft-status")).toContainText("このブラウザに保存済み");
  await page.reload();
  await expect(page.locator("#run-script-button")).toBeEnabled();
  await expect(page.getByRole("tab", { name: "無題", exact: true })).toHaveAttribute("aria-selected", "true");
  await expect(page.locator("#code-editor")).toHaveValue("answer = 42\n");
  await expect(page.locator("#project-file-tree [data-kind='file']")).toHaveCount(1);
  await page.locator("#save-draft-button").click();
  await expect(page.locator("#project-save-dialog")).toBeVisible();
});

test("creates directories under the selected parent and keeps invalid names in the dialog", async ({ page }) => {
  await page.goto("/");
  await expect(page.locator("#run-script-button")).toBeEnabled();
  await page.locator("#project-file-tools > summary").click();
  await page.locator("#project-root-select").click();
  await expect(page.locator("#project-file-rename")).toBeDisabled();
  await expect(page.locator("#project-file-delete")).toBeDisabled();
  await page.locator("#project-directory-create").click();
  const dialog = page.getByRole("dialog", { name: "ディレクトリを作成" });
  await expect(dialog).toContainText("親ディレクトリ: /project");
  await page.getByLabel("ディレクトリ名", { exact: true }).fill("lib");
  await dialog.getByRole("button", { name: "作成", exact: true }).click();
  await expect(dialog).toBeHidden();
  await expect(page.locator("#project-file-selection")).toHaveText("選択中: /project/lib");
  await page.locator("#project-directory-create").click();
  await expect(dialog).toContainText("親ディレクトリ: /project/lib");
  await page.getByLabel("ディレクトリ名", { exact: true }).fill("../escape");
  await dialog.getByRole("button", { name: "作成", exact: true }).click();
  await expect(dialog.getByRole("alert")).toBeVisible();
  await expect(page.locator("#project-file-tree [data-path='escape']")).toHaveCount(0);
  await page.getByLabel("ディレクトリ名", { exact: true }).fill("sensors");
  await page.getByLabel("ディレクトリ名", { exact: true }).press("Enter");
  await expect(dialog).toBeHidden();
  await expect(page.locator("#project-file-tree [data-path='lib/sensors']")).toBeVisible();
  await page.locator("#project-file-tree [data-path='main.py'] > .project-tree-row").click();
  await expect(page.locator("#project-directory-create")).toBeEnabled();
  await page.locator("#project-directory-create").click();
  await expect(dialog).toContainText("親ディレクトリ: /project");
  await page.getByLabel("ディレクトリ名", { exact: true }).fill("beside-main");
  await dialog.getByRole("button", { name: "作成", exact: true }).click();
  await expect(dialog).toBeHidden();
  await expect(page.locator("#project-file-tree [data-path='beside-main']")).toBeVisible();
  await expect(page.locator("#project-file-tree [data-path='main.py']")).toHaveAttribute("data-kind", "file");
  await page.reload();
  await expect(page.locator("#run-script-button")).toBeEnabled();
  await expect(page.locator("#project-file-tree [data-path='lib/sensors']")).toHaveCount(1);
  await expect(page.locator("#project-file-tree [data-path='beside-main']")).toHaveCount(1);
});

test("creates a directory beside a selected nested file and persists it", async ({ page }) => {
  await page.goto("/");
  await expect(page.locator("#run-script-button")).toBeEnabled();
  await page.locator("#repl-input").fill("import os; os.mkdir('lib'); open('lib/helper.py', 'w').write('answer = 7\\n'); print('sibling-fixture')");
  await page.locator("#send-button").click();
  await expect(page.locator("#terminal")).toContainText("sibling-fixture");
  await expect(page.locator("#run-script-button")).toBeEnabled();
  await page.locator("#project-file-tree [data-path='lib'] > .project-tree-row").click();
  const file = page.locator("#project-file-tree [data-path='lib/helper.py']");
  await file.locator(":scope > .project-tree-row").click();
  await expect(file).toBeFocused();
  await page.locator("#project-file-tools > summary").click();
  await page.locator("#project-directory-create").click();
  const dialog = page.getByRole("dialog", { name: "ディレクトリを作成" });
  await expect(dialog).toContainText("親ディレクトリ: /project/lib");
  await dialog.getByLabel("ディレクトリ名", { exact: true }).fill("sensors");
  await dialog.getByRole("button", { name: "作成", exact: true }).click();
  await expect(dialog).toBeHidden();
  await expect(page.locator("#project-file-tree [data-path='lib/sensors']")).toBeVisible();
  await expect(file).toHaveAttribute("data-kind", "file");
  await expect(page.locator("#project-file-tree [data-path='sensors']")).toHaveCount(0);
  await page.reload();
  await expect(page.locator("#run-script-button")).toBeEnabled();
  await expect(page.locator("#project-file-tree [data-path='lib/sensors']")).toHaveAttribute("data-kind", "directory");
  await page.locator("#repl-input").fill("import os; print('sibling-file', open('lib/helper.py').read()); print('sibling-directory', 'sensors' in os.listdir('lib'))");
  await page.locator("#send-button").click();
  await expect(page.locator("#terminal")).toContainText("sibling-file answer = 7");
  await expect(page.locator("#terminal")).toContainText("sibling-directory True");
});

test("renames files and directories with open descendants, rejects collisions and persists the new paths", async ({ page }) => {
  await page.goto("/");
  await expect(page.locator("#run-script-button")).toBeEnabled();
  await page.locator("#repl-input").fill("import os; os.mkdir('lib'); open('lib/helper.py', 'w').write('answer = 7\\n'); open('lib/taken.py', 'w').write('answer = 8\\n'); print('rename-fixture')");
  await page.locator("#send-button").click();
  await expect(page.locator("#terminal")).toContainText("rename-fixture");
  await expect(page.locator("#run-script-button")).toBeEnabled();
  await page.locator("#project-file-tree [data-path='lib'] > .project-tree-row").click();
  await page.locator("#project-file-tree [data-path='lib/helper.py'] > .project-tree-row").dblclick();
  await page.locator("#project-file-tools > summary").click();
  await page.locator("#project-file-rename").click();
  const fileDialog = page.getByRole("dialog", { name: "ファイル名の変更" });
  await expect(fileDialog.getByLabel("ファイル名", { exact: true })).toHaveValue("helper.py");
  await expect(fileDialog).toContainText("選択中: /project/lib/helper.py");
  await fileDialog.getByLabel("ファイル名", { exact: true }).fill("taken.py");
  await fileDialog.getByRole("button", { name: "変更", exact: true }).click();
  await expect(fileDialog.getByRole("alert")).toBeVisible();
  await expect(page.getByRole("tab", { name: "helper.py", exact: true })).toBeVisible();
  await fileDialog.getByLabel("ファイル名", { exact: true }).fill("sensor.py");
  await fileDialog.getByRole("button", { name: "変更", exact: true }).click();
  await expect(fileDialog).toBeHidden();
  await expect(page.getByRole("tab", { name: "sensor.py", exact: true })).toHaveAttribute("aria-selected", "true");
  await expect(page.locator("#code-editor")).toHaveValue("answer = 7\n");
  await page.locator("#project-file-tree [data-path='lib'] > .project-tree-row").click();
  await page.locator("#project-file-rename").click();
  const directoryDialog = page.getByRole("dialog", { name: "ディレクトリ名の変更" });
  await expect(page.getByLabel("ディレクトリ名", { exact: true })).toHaveValue("lib");
  await page.getByLabel("ディレクトリ名", { exact: true }).fill("drivers");
  await directoryDialog.getByRole("button", { name: "変更", exact: true }).click();
  await expect(directoryDialog).toBeHidden();
  await expect(page.locator("#project-file-tree [data-path='drivers/sensor.py']")).toHaveCount(1);
  await expect(page.locator("#project-file-tree [data-path^='lib']")).toHaveCount(0);
  await page.locator("#code-editor").fill("answer = 9\n");
  await expect(page.locator("#draft-status")).toContainText("このブラウザに保存済み");
  await page.reload();
  await expect(page.locator("#run-script-button")).toBeEnabled();
  await expect(page.getByRole("tab", { name: "sensor.py", exact: true })).toHaveAttribute("aria-selected", "true");
  await expect(page.locator("#code-editor")).toHaveValue("answer = 9\n");
  await page.locator("#repl-input").fill("import os; print('renamed-file', open('drivers/sensor.py').read()); print('old-path', 'lib' in os.listdir())");
  await page.locator("#send-button").click();
  await expect(page.locator("#terminal")).toContainText("renamed-file answer = 7");
  await expect(page.locator("#terminal")).toContainText("old-path False");
});

test("deletes files and empty directories directly and confirms recursive deletion without losing untitled drafts", async ({ page }) => {
  await page.goto("/");
  await expect(page.locator("#run-script-button")).toBeEnabled();
  await page.locator("#repl-input").fill("import os; os.mkdir('lib'); os.mkdir('lib/nested'); os.mkdir('empty'); os.mkdir('library'); open('lib/nested/helper.py', 'w').write('answer = 7\\n'); open('library/keep.py', 'w').write('kept'); open('delete.py', 'w').write('gone'); print('delete-fixture')");
  await page.locator("#send-button").click();
  await expect(page.locator("#terminal")).toContainText("delete-fixture");
  await expect(page.locator("#run-script-button")).toBeEnabled();
  await page.locator("#project-file-tree [data-path='lib'] > .project-tree-row").click();
  await page.locator("#project-file-tree [data-path='lib/nested'] > .project-tree-row").click();
  await page.locator("#project-file-tree [data-path='lib/nested/helper.py'] > .project-tree-row").dblclick();
  await page.locator("#project-file-tools > summary").click();
  await page.locator("#project-file-create").click();
  await page.locator("#code-editor").fill("keep_draft = 42\n");
  await expect(page.locator("#draft-status")).toContainText("このブラウザに保存済み");
  let confirmation = "";
  page.once("dialog", async dialog => { confirmation = dialog.message(); await dialog.dismiss(); });
  await page.locator("#project-file-tree [data-path='lib'] > .project-tree-row").click();
  await page.locator("#project-file-delete").click();
  await expect(page.locator("#project-file-delete")).toBeEnabled();
  expect(confirmation).toContain("まとめて削除");
  await expect(page.locator("#project-file-tree [data-path='lib/nested/helper.py']")).toHaveCount(1);
  await expect(page.getByRole("tab", { name: "helper.py", exact: true })).toBeVisible();
  page.once("dialog", dialog => dialog.accept());
  await page.locator("#project-file-delete").click();
  await expect(page.locator("#project-file-tree [data-path='lib']")).toHaveCount(0);
  await expect(page.getByRole("tab", { name: "helper.py", exact: true })).toHaveCount(0);
  await expect(page.getByRole("tab", { name: "無題", exact: true })).toHaveAttribute("aria-selected", "true");
  await expect(page.locator("#code-editor")).toHaveValue("keep_draft = 42\n");
  let unexpectedConfirmation = false;
  page.on("dialog", async dialog => { unexpectedConfirmation = true; await dialog.dismiss(); });
  for (const path of ["delete.py", "empty"]) {
    await page.locator(`#project-file-tree [data-path='${path}'] > .project-tree-row`).click();
    await page.locator("#project-file-delete").click();
    await expect(page.locator(`#project-file-tree [data-path='${path}']`)).toHaveCount(0);
  }
  expect(unexpectedConfirmation).toBe(false);
  await page.reload();
  await expect(page.locator("#run-script-button")).toBeEnabled();
  await expect(page.locator("#code-editor")).toHaveValue("keep_draft = 42\n");
  await expect(page.locator("#project-file-tree [data-path='library/keep.py']")).toHaveCount(1);
  await expect(page.locator("#project-file-tree [data-path='lib'], #project-file-tree [data-path='delete.py'], #project-file-tree [data-path='empty']")).toHaveCount(0);
});
