import { expect, test } from "./workspace-test";

for (const width of [1280, 320]) {
  test(`moves an open file into a nested directory and back to the root at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 720 });
    await page.goto("/");
    await expect(page.locator("#run-script-button")).toBeEnabled();
    await page.locator("#repl-input").fill("import os; os.mkdir('target'); os.mkdir('target/nested'); open('helper.py', 'w').write('answer = 7\\n'); print('file-move-fixture')");
    await page.locator("#send-button").click();
    await expect(page.locator("#terminal")).toContainText("file-move-fixture");
    await expect(page.locator("#run-script-button")).toBeEnabled();
    await page.locator("#project-file-tools > summary").click();
    await page.locator("#project-root-select").click();
    await expect(page.locator("#project-file-move")).toBeDisabled();
    await page.locator("#project-file-tree [data-path='helper.py'] > .project-tree-row").dblclick();
    await page.locator("#project-file-move").click();
    const dialog = page.getByRole("dialog", { name: "ファイル・ディレクトリの移動" });
    const destination = dialog.getByLabel("移動先ディレクトリ", { exact: true });
    await expect(dialog).toContainText("移動元: /project/helper.py");
    await expect(dialog.getByRole("button", { name: "移動", exact: true })).toBeDisabled();
    await destination.selectOption("target/nested");
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);
    await dialog.getByRole("button", { name: "移動", exact: true }).click();
    await expect(dialog).toBeHidden();
    await expect(page.locator("#project-file-tree [data-path='helper.py']")).toHaveCount(0);
    await expect(page.locator("#project-file-tree [data-path='target/nested/helper.py']")).toBeVisible();
    await expect(page.getByRole("tab", { name: "helper.py", exact: true })).toHaveAttribute("aria-selected", "true");
    await expect(page.locator("#code-editor")).toHaveValue("answer = 7\n");
    await page.locator("#code-editor").fill("answer = 9\n");
    await page.locator("#project-file-save").click();
    await expect(page.locator("#project-file-save")).toBeEnabled();
    await page.reload();
    await expect(page.locator("#run-script-button")).toBeEnabled();
    await expect(page.getByRole("tab", { name: "helper.py", exact: true })).toHaveAttribute("aria-selected", "true");
    await expect(page.locator("#code-editor")).toHaveValue("answer = 9\n");
    await page.locator("#project-file-tools > summary").click();
    await page.locator("#project-file-tree [data-path='target'] > .project-tree-row").click();
    await page.locator("#project-file-tree [data-path='target/nested'] > .project-tree-row").click();
    await page.locator("#project-file-tree [data-path='target/nested/helper.py'] > .project-tree-row").click();
    await page.locator("#project-file-move").click();
    await expect(destination).toHaveValue("target/nested");
    await destination.selectOption("");
    await dialog.getByRole("button", { name: "移動", exact: true }).click();
    await expect(dialog).toBeHidden();
    await expect(page.locator("#project-file-tree [data-path='helper.py']")).toBeVisible();
    await expect(page.locator("#project-file-tree [data-path='target/nested/helper.py']")).toHaveCount(0);
    await page.reload();
    await expect(page.locator("#run-script-button")).toBeEnabled();
    await page.locator("#repl-input").fill("import os; print('moved-content', open('helper.py').read()); print('old-file', 'helper.py' in os.listdir('target/nested'))");
    await page.locator("#send-button").click();
    await expect(page.locator("#terminal")).toContainText("moved-content answer = 9");
    await expect(page.locator("#terminal")).toContainText("old-file False");
  });
}

test("moves a directory subtree and its open tabs while excluding invalid destinations", async ({ page }) => {
  await page.goto("/");
  await expect(page.locator("#run-script-button")).toBeEnabled();
  await page.locator("#repl-input").fill("import os; os.mkdir('pkg'); os.mkdir('pkg/nested'); os.mkdir('pkg/empty'); os.mkdir('pkg-other'); os.mkdir('target'); open('pkg/nested/helper.py', 'w').write('answer = 7\\n'); open('pkg/other.py', 'w').write('value = 8\\n'); print('directory-move-fixture')");
  await page.locator("#send-button").click();
  await expect(page.locator("#terminal")).toContainText("directory-move-fixture");
  await expect(page.locator("#run-script-button")).toBeEnabled();
  await page.locator("#project-file-tree [data-path='pkg'] > .project-tree-row").click();
  await page.locator("#project-file-tree [data-path='pkg/nested'] > .project-tree-row").click();
  await page.locator("#project-file-tree [data-path='pkg/nested/helper.py'] > .project-tree-row").dblclick();
  await page.locator("#project-file-tree [data-path='pkg/other.py'] > .project-tree-row").dblclick();
  await page.locator("#project-file-tools > summary").click();
  await page.locator("#project-file-create").click();
  await page.locator("#code-editor").fill("keep_draft = 42\n");
  await expect(page.locator("#draft-status")).toContainText("このブラウザに保存済み");
  await page.locator("#project-file-tree [data-path='pkg'] > .project-tree-row").click();
  await page.locator("#project-file-move").click();
  const dialog = page.locator("#project-move-dialog");
  const destination = dialog.getByLabel("移動先ディレクトリ", { exact: true });
  await expect(destination.locator("option")).toHaveText(["/project", "/project/pkg-other", "/project/target"]);
  await destination.selectOption("target");
  await dialog.getByRole("button", { name: "移動", exact: true }).click();
  await expect(dialog).toBeHidden();
  await expect(page.locator("#project-file-selection")).toHaveText("選択中: /project/target/pkg");
  await expect(page.locator("#project-file-tree [data-path='pkg']")).toHaveCount(0);
  await expect(page.locator("#project-file-tree [data-path='target/pkg/nested/helper.py']")).toHaveCount(1);
  await expect(page.locator("#project-file-tree [data-path='target/pkg/empty']")).toHaveAttribute("data-kind", "directory");
  await expect(page.getByRole("tab", { name: "無題", exact: true })).toHaveAttribute("aria-selected", "true");
  await expect(page.locator("#code-editor")).toHaveValue("keep_draft = 42\n");
  await page.getByRole("tab", { name: "helper.py", exact: true }).click();
  await expect(page.getByRole("tab", { name: "helper.py", exact: true })).toHaveAttribute("title", "/project/target/pkg/nested/helper.py");
  await page.locator("#code-editor").fill("answer = 9\n");
  await page.locator("#project-file-save").click();
  await expect(page.locator("#project-file-save")).toBeEnabled();
  await page.reload();
  await expect(page.locator("#run-script-button")).toBeEnabled();
  await expect(page.getByRole("tab", { name: "other.py", exact: true })).toHaveAttribute("title", "/project/target/pkg/other.py");
  await expect(page.locator("#project-file-tree [data-path='pkg-other']")).toHaveCount(1);
  await page.locator("#repl-input").fill("import os; print('moved-helper', open('target/pkg/nested/helper.py').read()); print('moved-other', open('target/pkg/other.py').read()); print('old-directory', 'pkg' in os.listdir())");
  await page.locator("#send-button").click();
  await expect(page.locator("#terminal")).toContainText("moved-helper answer = 9");
  await expect(page.locator("#terminal")).toContainText("moved-other value = 8");
  await expect(page.locator("#terminal")).toContainText("old-directory False");
});

test("cancels a move, rejects name collisions and retries after storage failure without changing the original", async ({ page }) => {
  await page.goto("/");
  await expect(page.locator("#run-script-button")).toBeEnabled();
  await page.locator("#repl-input").fill("import os; os.mkdir('a'); os.mkdir('b'); os.mkdir('c'); open('a/helper.py', 'w').write('answer = 7\\n'); open('b/helper.py', 'w').write('answer = 8\\n'); print('move-retry-fixture')");
  await page.locator("#send-button").click();
  await expect(page.locator("#terminal")).toContainText("move-retry-fixture");
  await expect(page.locator("#run-script-button")).toBeEnabled();
  await page.locator("#project-file-tree [data-path='a'] > .project-tree-row").click();
  await page.locator("#project-file-tree [data-path='a/helper.py'] > .project-tree-row").dblclick();
  await page.locator("#project-file-tools > summary").click();
  // Flush the new tab's autosave before injecting a failure into the move itself.
  await page.locator("#project-file-save").click();
  await expect(page.locator("#project-file-save")).toBeEnabled();
  await page.locator("#project-file-move").click();
  const dialog = page.locator("#project-move-dialog");
  const destination = dialog.getByLabel("移動先ディレクトリ", { exact: true });
  await destination.selectOption("b");
  await dialog.getByRole("button", { name: "キャンセル", exact: true }).click();
  await expect(dialog).toBeHidden();
  await expect(page.locator("#project-file-tree [data-path='a/helper.py']")).toHaveCount(1);
  await page.locator("#project-file-move").click();
  await destination.selectOption("b");
  await dialog.getByRole("button", { name: "移動", exact: true }).click();
  await expect(dialog.getByRole("alert")).toContainText("既に存在");
  await expect(page.getByRole("tab", { name: "helper.py", exact: true })).toHaveAttribute("title", "/project/a/helper.py");
  await destination.selectOption("c");
  await page.evaluate(() => {
    const put = IDBObjectStore.prototype.put;
    IDBObjectStore.prototype.put = function(...args: Parameters<typeof put>) {
      IDBObjectStore.prototype.put = put;
      throw new DOMException("forced move failure", "QuotaExceededError");
    };
  });
  await dialog.getByRole("button", { name: "移動", exact: true }).click();
  await expect(dialog.getByRole("alert")).toContainText("forced move failure");
  await expect(page.locator("#project-file-tree [data-path='a/helper.py']")).toHaveCount(1);
  await expect(page.locator("#project-file-tree [data-path='c/helper.py']")).toHaveCount(0);
  await expect(page.getByRole("tab", { name: "helper.py", exact: true })).toHaveAttribute("title", "/project/a/helper.py");
  await dialog.getByRole("button", { name: "移動", exact: true }).click();
  await expect(dialog).toBeHidden();
  await expect(page.getByRole("tab", { name: "helper.py", exact: true })).toHaveAttribute("title", "/project/c/helper.py");
  await page.reload();
  await expect(page.locator("#run-script-button")).toBeEnabled();
  await page.locator("#repl-input").fill("print('moved-original', open('c/helper.py').read()); print('kept-collision', open('b/helper.py').read())");
  await page.locator("#send-button").click();
  await expect(page.locator("#terminal")).toContainText("moved-original answer = 7");
  await expect(page.locator("#terminal")).toContainText("kept-collision answer = 8");
});
